// ITEMS
export const ITEMS_REQUEST = "ITEMS_REQUEST";
export const ITEMS_DATA = "ITEMS_DATA";
export const ITEMS_ERROR = "ITEMS_ERROR";

// COMPANIES
export const COMPANIES_REQUEST = "COMPANIES_REQUEST";
export const COMPANIES_DATA = "COMPANIES_DATA";
export const COMPANIES_ERROR = "COMPANIES_ERROR";

// CURRENT ITEMS
export const CURRENT_ITEMS_DATA = "CURRENT_ITEMS_DATA";

// SORTED BRANDS
export const BRANDS_ITEMS = "BRANDS_ITEMS";
export const SORTED_BRANDS_DATA = "SORTED_BRANDS_DATA";

// SORTED ITEMS
export const SORTED_ITEMS_DATA = "SORTED_ITEMS_DATA";
export const SORTED_ITEMS_CLICKED = "SORTED_ITEMS_CLICKED";

// BASKET
export const ADD_ITEMS_BASKET = "ADD_ITEMS_BASKET";
export const DELETE_ITEMS_BASKET = "DELETE_ITEMS_BASKET";
export const BASKET_ADD_CLICKED = "BASKET_ADD_CLICKED";

// LOADING LOCK
export const LOADING_LOCK = "LOADING_LOCK";
