// ITEMS
export const ITEMS_REQUEST = "ITEMS_REQUEST";
export const ITEMS_DATA = "ITEMS_DATA";
export const ITEMS_ERROR = "ITEMS_ERROR";

// COMPANIES
export const COMPANIES_REQUEST = "COMPANIES_REQUEST";
export const COMPANIES_DATA = "COMPANIES_DATA";
export const COMPANIES_ERROR = "COMPANIES_ERROR";
